### ISSUE TITLE
indigo-devel branch?

### ISSUE THREAD

**Issue by wkentaro** [PR2/pr2_robot#234]
Why does this repo have no indigo-devel branch?

**Comment by wkentaro** [comment]
where can I send PR which is indigo specific?

**Comment by UltronDestroyer** [comment]
"Why does this repo have no indigo-devel branch?"

It appears that no code was in development for indigo-devel (hence the name Indigo development). 

Do you want me to create indigo-devel so you can make a PR?

**Comment by wkentaro** [comment]
Now I'm trying upgrade the ROS version inside PR2, from hydro to indigo.
I think I should change some codes for this, for example `queue_size` for publishers.
http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers

And yes, I'm willing to make PRs to this repo.

**Comment by UltronDestroyer** [comment]
Hmm, I think the queue_size stuff only returned warnings for compilers. Was there any problems compiling this by source for you?

**Comment by wkentaro** [comment]
I'm just at starting point for the installation, so I'm not sure how many changes are there.
And I needed to change like https://github.com/PR2/pr2_robot/pull/235 for indigo.

**Comment by wkentaro** [comment]
> I think the queue_size stuff only returned warnings for compilers.

I'm distracted by the syntax warning about `queue_size` at runtime.
It appears all times..
