### ISSUE TITLE
pr2_computer_monitor should install mpstat

### ISSUE THREAD

**Issue by garaemon** [PR2/pr2_robot#236]
pr2_computer_monitor uses mpstat commands but it is not installed.
mpstat can be installed by `sudo apt-get install sysstat`.

**Comment by mherrb** [comment]
ipmitool is useless on the robots with the Clearpath Robotics upgrade. There is no IMPI  on the new motherboards.
Normally systat is the dependecies of pr2-environment. But it won't hurt to also add it as a dependency here.

**Comment by mherrb** [comment]
Oops I missed that this was already merged. So the issue can be closed.
