### ISSUE TITLE
Some pr2 packages seem to be missing ?

### ISSUE THREAD

**Issue by addy1997** [PR2/pr2_robot#260]
I have made a repository with all the packages at one place which makes it comparatively simple to install PR2_moveit.
Here is the link - https://github.com/addy1997/pr2_ROS.git

**Comment by v4hn** [comment]
The classical mechanism to collect repositories like this is using [`wstool`](https://pypi.org/project/wstool/) (or, nowadays, [`vcs`](https://pypi.org/project/vcstool/)) to create a yaml file that contains all information on the repositories.

Also, I have no idea how you managed to do it, but the submodules you added in your linked repository do not have urls associated.
