### ISSUE TITLE
Problems with building the Package

### ISSUE THREAD

**Issue by ghost** [PR2/pr2_robot#267]
I've created a new catkin WS and cloned the project in the src folder, when trying to build the project i got this error:

"-- +++ processing catkin package: 'pr2_run_stop_auto_restart'
-- ==> add_subdirectory(pr2_robot/pr2_run_stop_auto_restart)
-- Could NOT find pr2_msgs (missing: pr2_msgs_DIR)
-- Could not find the required component 'pr2_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "pr2_msgs" with any
  of the following names:

    pr2_msgsConfig.cmake
    pr2_msgs-config.cmake

  Add the installation prefix of "pr2_msgs" to CMAKE_PREFIX_PATH or set
  "pr2_msgs_DIR" to a directory containing one of the above files.  If
  "pr2_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  pr2_robot/pr2_run_stop_auto_restart/CMakeLists.txt:6 (find_package)"

In the CMakeLists file of the package "pr2_run_stop_auto_restart" is a component required called pr2_msgs that is somehow not found, does someone had that problem,too?

**Comment by v4hn** [comment]
You are missing [`pr2_common`](https://github.com/PR2/pr2_common).
